// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * This file is the editable surface for custom backend logic that
 * doesn't fit the auto-generated CRUD model (per-model GET/POST/PATCH/
 * DELETE under `/api/<model>s`). Anything you mount on the exported
 * Hono app shows up at `/api/...` alongside the generated CRUD routes.
 *
 * Examples:
 *   - Aggregations / dashboards: `app.get('/dashboard', ...)`
 *   - Webhooks: `app.post('/webhooks/stripe', ...)`
 *   - Auth flows: `app.post('/auth/login', ...)`
 *
 * For installed integrations (Jira, Slack, Google, Meta Ads, etc.):
 *
 * - Dashboards / list views / "my X" pages → mount a route HERE that
 *   uses `getServerToolsClient()`. Resolve identity per request with
 *   `<TOOLKIT>_GET_CURRENT_USER`, compose the calls you need, return
 *   a clean shape your component owns.
 *
 *   The SDK auto-parses tool result `data` on success (the runtime
 *   JSON.stringifies tool responses; @shogo-ai/sdk/tools >=1.3 parses
 *   them back). Index `data` like a plain object — do NOT write a
 *   `JSON.parse(result.data)` helper. Pass a generic to `execute<T>()`
 *   for typed access.
 *
 *   import { getServerToolsClient } from '@shogo-ai/sdk/tools'
 *
 *   app.get('/jira/my-issues', async (c) => {
 *     const tools = getServerToolsClient()
 *     const me = await tools.execute<{ accountId: string }>('JIRA_GET_CURRENT_USER', {})
 *     if (!me.ok || !me.data?.accountId) {
 *       return c.json({ error: me.error ?? 'not authenticated' }, 401)
 *     }
 *     const issues = await tools.execute<{ issues: unknown[] }>('JIRA_SEARCH_ISSUES', {
 *       jql: `assignee = "${me.data.accountId}"`,
 *     })
 *     if (!issues.ok) return c.json({ error: issues.error ?? 'search failed' }, 502)
 *     return c.json({ issues: issues.data?.issues ?? [] })
 *   })
 *
 *   In the browser, surface the server's `error` field — never throw
 *   `new Error('Failed to load X')`:
 *
 *     const res = await fetch('/api/jira/my-issues')
 *     const body = await res.json().catch(() => ({}))
 *     if (!res.ok) setError(body.error ?? `HTTP ${res.status}`)
 *     else setIssues(body.issues ?? [])
 *
 *   After writing or editing a route, hit it to confirm shape + status:
 *     curl -s -w "\nHTTP %{http_code}\n" http://localhost:$RUNTIME_PORT/api/jira/my-issues
 *   A green build proves the file compiled, not that the endpoint works.
 *
 * - Ad-hoc interactive actions (button clicks, form submits) → use
 *   `useTools()` directly in the component. Don't add a route here for
 *   single-call passthroughs.
 *
 * Hand-rolling a `fetch()` to the provider's REST API will fail
 * because the pod has no provider tokens — auth lives in the runtime.
 * NEVER hardcode the agent operator's identity (accountId, member id,
 * userId) into route code; resolve it per request as shown above.
 *
 * The runtime watches this file. Saving triggers a fast restart of
 * `server.tsx` (no schema regeneration, no `prisma db push`) so changes
 * land in under a second.
 *
 * The Prisma client is available — import it from `./src/lib/db`:
 *
 *   import { prisma } from './src/lib/db'
 *
 *   app.get('/stats', async (c) => {
 *     const userCount = await prisma.user.count()
 *     return c.json({ userCount })
 *   })
 *
 * Do NOT edit `server.tsx` — it is auto-generated by the SDK from
 * `shogo.config.json` and will be overwritten on the next regeneration.
 */

import { Hono } from 'hono'
import { prisma } from './src/lib/db'

const app = new Hono()

const GENRES = [
  'Bass Boosted', 'Hindi Devotional', 'Punjabi Bhangra', 'English Trance',
  'Racing Motivation', 'Gym Workout', 'Bhojpuri Remix', 'English Rap',
  'Global Trance Remix', 'Desi Hip Hop', 'Spiritual Meditation',
  'Hindi Pop Remix', 'Punjabi Pop', 'Car Racing Bass', 'Gym Rep Music', 'Devotional Fusion'
]

const LANGUAGES = ['Hindi', 'English', 'Punjabi', 'Bhojpuri', 'Hinglish']

const SCRIPT_TEMPLATES: Record<string, string[]> = {
  lyrics: [
    'Fire 🔥 Bass Boosted {genre} Mix — Full Power Workout Song',
    'Nonstop {genre} Energy — Gym Motivation {lang} Lyrics',
    '{genre} Remastered 2026 — Heavy Bass Official Music',
    'Epic {genre} Mashup — Racing Energy {lang} Vibes',
    '{genre} Super Hit — Dance Floor Banger {lang} Track',
  ],
  title: [
    '🔥 {genre} Bass Boosted 2026 | {lang} Workout Music #shorts',
    '{genre} Nonstop Mix | Heavy Bass {lang} DJ Remix 2026',
    'BEST {genre} Songs 2026 | {lang} Motivational Music Collection',
    '🚨 {genre} Bass BOOSTED 10 Hours | {lang} Gym Energy Playlist',
    'VIRAL {genre} Remix | {lang} Party Dance Music 2026',
  ],
  description: [
    'Welcome to BittuSinghOfficialYT! 🎬\n\n🎵 {genre} Collection — {lang} Language\n🔊 Heavy Bass Boosted for Maximum Energy\n💪 Perfect for Gym, Racing, Workout & Party\n\n#BittuSinghOfficialYT #{genre} #BassBoosted #{lang}Music #WorkoutMusic #2026',
    '🎧 {genre} {lang} Mix 2026 — Full Power Session\n\n⚡ Subscribe for daily {genre} content\n🔥 Like & Share if you felt the bass!\n\n🎵 Track: {genre} Official Mix\n🌍 Global Audience | All Languages\n\n#BittuSinghOfficialYT #{genre} #{lang}',
  ],
  seo: [
    'SEO: {genre} is trending with 2M+ monthly searches. Use tags: {genre} 2026, {genre} bass boosted, {lang} music, workout music, gym motivation. Best upload time: 6PM IST. Thumbnail style: Dark with neon glow text.',
    'SEO Report: {genre} content peaks on weekends. Target keywords: "{genre} remix {lang}", "bass boosted {lang} songs", "{genre} workout music". Hashtags: #BittuSinghOfficialYT #Viral #{genre}',
  ],
}

const IDEA_TEMPLATES = [
  '🎵 {genre} {lang} Bass Boosted Mix — Full Album Release',
  '🎬 {genre} Music Video — Gym Motivation Story',
  '📊 Top 50 {genre} Songs {lang} — Ultimate Compilation',
  '🔥 {genre} vs {genre2} — Epic Bass Battle',
  '💪 {genre} Workout Playlist — 2 Hour Nonstop Mix',
  '🏎️ {genre} Car Racing Energy — Drive Mode Music',
  '🧘 {genre} Meditation Remix — Spiritual Bass Experience',
  '🎤 {genre} Live Performance — Studio Session {lang}',
  '📈 {genre} Trending Shorts — 60 Second Fire Mix',
  '🌍 {genre} Global Collaboration — Multi Language Mix',
]

function fillTemplate(template: string, vars: { genre: string; genre2?: string; lang: string }): string {
  return template
    .replace(/{genre}/g, vars.genre)
    .replace(/{genre2}/g, vars.genre2 || GENRES[Math.floor(Math.random() * GENRES.length)])
    .replace(/{lang}/g, vars.lang)
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

function pickN<T>(arr: T[], n: number): T[] {
  const shuffled = [...arr].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, n)
}

// ─── AUTOPILOT: Run one automation cycle ────────────────────────
app.post('/autopilot/run', async (c) => {
  const results: string[] = []

  // 1. Auto-generate a script
  const genre = pick(GENRES)
  const lang = pick(LANGUAGES)
  const templates = SCRIPT_TEMPLATES.lyrics
  const title = fillTemplate(pick(templates), { genre, lang })

  const script = await prisma.contentScript.create({
    data: {
      videoTitle: title,
      videoType: pick(['lyrics', 'description', 'seo']),
      genre,
      language: lang,
      content: `${title}\n\nAuto-generated by BittuSinghOfficialYT AI Agent\nGenre: ${genre}\nLanguage: ${lang}\nTimestamp: ${new Date().toISOString()}\n\n---\nThis script was created automatically. Edit and refine before publishing.`,
      tags: `${genre}, ${lang}, Bass Boosted, Workout, BittuSinghOfficialYT, ${genre} Mix 2026`,
      mood: pick(['energetic', 'powerful', 'motivational', 'intense', 'uplifting']),
      status: 'ready',
    },
  })
  results.push(`✅ Script: "${title}" (${genre} / ${lang})`)

  // 2. Auto-generate a video idea
  const genre2 = pick(GENRES.filter(g => g !== genre))
  const ideaTitle = fillTemplate(pick(IDEA_TEMPLATES), { genre, genre2, lang })
  const idea = await prisma.videoIdea.create({
    data: {
      title: ideaTitle,
      description: `Auto-generated idea for ${genre} content in ${lang}. Priority content based on trending genre analysis. Potential audience: Global music lovers, gym enthusiasts, racing fans.`,
      category: genre,
      priority: Math.floor(Math.random() * 3) + 3,
      estimatedEffort: pick(['short', 'medium', 'long']),
      status: 'new',
    },
  })
  results.push(`💡 Idea: "${ideaTitle}"`)

  // 3. Auto-add to upload queue
  const seoTitle = fillTemplate(pick(SCRIPT_TEMPLATES.title), { genre, lang })
  const queueItem = await prisma.uploadQueue.create({
    data: {
      videoTitle: seoTitle,
      genre,
      language: lang,
      videoType: pick(['music_video', 'shorts', 'mix', 'remix']),
      status: 'pending',
      scheduledTime: `${pick(['06:00', '12:00', '18:00', '21:00'])} IST`,
      platform: pick(['YouTube', 'YouTube', 'YouTube', 'Instagram Reels', 'TikTok']),
      notes: `Auto-queued by AI Agent. Genre: ${genre}. Language: ${lang}.`,
    },
  })
  results.push(`📤 Upload Queued: "${seoTitle}" on ${queueItem.platform}`)

  // 4. Create/Update automation task
  const task = await prisma.automationTask.create({
    data: {
      type: 'generate_script',
      title: `Auto-cycle: ${genre} ${lang}`,
      description: results.join('\n'),
      genre,
      language: lang,
      status: 'completed',
      priority: 4,
      result: JSON.stringify({ scriptId: script.id, ideaId: idea.id, queueId: queueItem.id }),
      runsCount: 1,
      lastRunAt: new Date(),
      nextRunAt: new Date(Date.now() + 30 * 60 * 1000),
      isRecurring: true,
      intervalMins: 30,
    },
  })

  return c.json({
    ok: true,
    message: `🤖 AutoPilot cycle complete! Generated ${results.length} items.`,
    task: task.id,
    results,
    stats: {
      totalScripts: await prisma.contentScript.count(),
      totalIdeas: await prisma.videoIdea.count(),
      totalQueued: await prisma.uploadQueue.count(),
      totalTasks: await prisma.automationTask.count(),
    },
  })
})

// ─── AUTOPILOT: Batch run (generate multiple at once) ──────────
app.post('/autopilot/batch', async (c) => {
  const body = await c.req.json().catch(() => ({}))
  const count = Math.min(body.count || 5, 20)
  const allResults: string[] = []

  for (let i = 0; i < count; i++) {
    const genre = pick(GENRES)
    const lang = pick(LANGUAGES)

    await prisma.contentScript.create({
      data: {
        videoTitle: fillTemplate(pick(SCRIPT_TEMPLATES.lyrics), { genre, lang }),
        videoType: pick(['lyrics', 'description', 'seo']),
        genre,
        language: lang,
        content: `Auto-generated ${genre} ${lang} script. Ready for recording.`,
        tags: `${genre}, ${lang}, Bass Boosted, BittuSinghOfficialYT`,
        status: 'ready',
      },
    })

    const ideaTitle = fillTemplate(pick(IDEA_TEMPLATES), { genre, lang })
    await prisma.videoIdea.create({
      data: {
        title: ideaTitle,
        description: `Auto-generated ${genre} content idea in ${lang}`,
        category: genre,
        priority: Math.floor(Math.random() * 3) + 3,
        status: 'new',
      },
    })

    await prisma.uploadQueue.create({
      data: {
        videoTitle: fillTemplate(pick(SCRIPT_TEMPLATES.title), { genre, lang }),
        genre,
        language: lang,
        status: 'pending',
        scheduledTime: `${pick(['06:00', '12:00', '18:00', '21:00'])} IST`,
        platform: 'YouTube',
      },
    })

    allResults.push(`✅ Cycle ${i + 1}: ${genre} / ${lang}`)
  }

  await prisma.automationTask.create({
    data: {
      type: 'generate_script',
      title: `Batch run: ${count} items`,
      description: allResults.join('\n'),
      status: 'completed',
      priority: 5,
      result: JSON.stringify({ generated: count }),
      runsCount: 1,
      lastRunAt: new Date(),
    },
  })

  return c.json({
    ok: true,
    message: `🤖 Batch complete! Generated ${count} scripts, ideas, and upload entries.`,
    results: allResults,
    stats: {
      totalScripts: await prisma.contentScript.count(),
      totalIdeas: await prisma.videoIdea.count(),
      totalQueued: await prisma.uploadQueue.count(),
      totalTasks: await prisma.automationTask.count(),
    },
  })
})

// ─── AUTOPILOT: Dashboard stats ─────────────────────────────────
app.get('/autopilot/stats', async (c) => {
  const [totalScripts, totalIdeas, totalQueued, totalTasks, completedTasks, failedTasks] = await Promise.all([
    prisma.contentScript.count(),
    prisma.videoIdea.count(),
    prisma.uploadQueue.count(),
    prisma.automationTask.count(),
    prisma.automationTask.count({ where: { status: 'completed' } }),
    prisma.automationTask.count({ where: { status: 'failed' } }),
  ])

  const recentTasks = await prisma.automationTask.findMany({
    orderBy: { createdAt: 'desc' },
    take: 10,
  })

  const pendingUploads = await prisma.uploadQueue.count({ where: { status: 'pending' } })
  const uploadedCount = await prisma.uploadQueue.count({ where: { status: 'uploaded' } })
  const approvedIdeas = await prisma.videoIdea.count({ where: { status: 'approved' } })
  const readyScripts = await prisma.contentScript.count({ where: { status: 'ready' } })

  return c.json({
    ok: true,
    stats: {
      totalScripts,
      totalIdeas,
      totalQueued,
      totalTasks,
      completedTasks,
      failedTasks,
      pendingUploads,
      uploadedCount,
      approvedIdeas,
      readyScripts,
      successRate: totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0,
    },
    recentTasks,
  })
})

// ─── AUTOPILOT: Toggle recurring task ───────────────────────────
app.patch('/autopilot/task/:id', async (c) => {
  const id = c.req.param('id')
  const body = await c.req.json().catch(() => ({}))

  const task = await prisma.automationTask.update({
    where: { id },
    data: {
      isRecurring: body.isRecurring ?? undefined,
      intervalMins: body.intervalMins ?? undefined,
      priority: body.priority ?? undefined,
      status: body.status ?? undefined,
    },
  })

  return c.json({ ok: true, task })
})

// ─── AUTOPILOT: Get all automation tasks ────────────────────────
app.get('/autopilot/tasks', async (c) => {
  const tasks = await prisma.automationTask.findMany({
    orderBy: { createdAt: 'desc' },
    take: 50,
  })
  return c.json({ ok: true, items: tasks, total: tasks.length })
})

export default app
